# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: marjorie.j.lucas@jpl.nasa.gov
author_name: Marjorie Lucas
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: maap-jupyter-server-extension
project_short_description: A JupyterLab extension.
python_name: maap_jupyter_server_extension
repository: ''
test: true

